source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'azure-search-basics' do

  pod 'Alamofire', '~> 3.0'
  pod 'FLEX', '~> 2.0', :configurations => ['Debug']

end

target 'azure-search-basicsTests' do

end

target 'azure-search-basicsUITests' do

end

